### ISSUE TITLE
What are the limitations on weights for chains?

### ISSUE THREAD

**Issue by fbeutler** [cmbant/getdist#17]
Hi 

I am trying to plot an MCMC chain using a weight array. 

samples_z1_prior = MCSamples(samples=data['alpha_z1_phi_mcmc_array'], settings={'min_weight_ratio': 0.}, weights=np.array(data['weight_phi_mcmc']), names=names, label='$\\alpha_{z1}-\\beta$ + Planck')

if I set the weight to 1 it all works fine, but with a more general weight, I get the error below. I tried to understand how the chain attribute is generated and was wondering whether the min_weight_ratio parameter is to blame. I set it manually, but I it seems to ignore the settings I manually provided.

Here is an example how my weights look like

print("max = ", np.array(data['weight_phi_mcmc']).max())
print(data['weight_phi_mcmc'][0:10])

which gives 

max =  6414.85520303
[65.864298022348777, 7.2310938431376631e-06, 1.0581215950983385e-10, 2.1621493843613816e-12, 0.18661013087037484, 9.5650192664169318e-06, 4.6463562589190878e-66, 2.7431270996436689e-27, 3.2501214203430937, 10.842194755581344]

and the error message I get is

Traceback (most recent call last):
  File "process_MCMC.py", line 234, in <module>
    main()
  File "process_MCMC.py", line 210, in main
    samples_z1_prior = MCSamples(samples=data['alpha_z1_phi_mcmc_array'], settings={'min_weight_ratio': 0.}, weights=np.array(data['weight_phi_mcmc']), names=names, label='$\\alpha_{z1}-\\beta$ + Planck')
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/mcsamples.py", line 137, in __init__
    Chains.__init__(self, root, jobItem=jobItem, **kwargs)
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/chains.py", line 817, in __init__
    WeightedSamples.__init__(self, **kwargs)
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/chains.py", line 168, in __init__
    self.setSamples(samples, weights, loglikes)
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/chains.py", line 223, in setSamples
    self.setMinWeightRatio(min_weight_ratio)
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/chains.py", line 748, in setMinWeightRatio
    self.filter(self.weights > max_weight * min_weight_ratio)
  File "/Users/xflorian/anaconda/envs/nbodykit-env/lib/python3.6/site-packages/getdist/chains.py", line 855, in filter
    if self.chains is None:
AttributeError: 'MCSamples' object has no attribute 'chains'

thanks
Florian

**Comment by cmbant** [comment]
This looks like https://github.com/cmbant/getdist/commit/5baeea7d38a217f6668cb98ef08150f3a017fb93
-are you using latest github version?

**Comment by fbeutler** [comment]
Hi Antony,

Indeed a pip install getdist --upgrade solved the problem.

thanks
Florian

thanks
