### ISSUE TITLE
TypeError: arguments did not match any overloaded call

### ISSUE THREAD

**Issue by jdh4** [cmbant/getdist#43]
RHEL 7.7, x86-64
getdist 1.1.0

The software was installed using conda:

conda create --name gd-env -c conda-forge python=3.7 scipy pandas matplotlib PySide2 pyyaml
conda activate gd-env
pip install getdist

When trying to make any kind of plot it gives an error:

$ getdist-gui -v
2020-04-27 14:22:45 [DEBUG]	[mainwindow.py:1302]		Param: chains
2020-04-27 14:23:08 [DEBUG]	[mainwindow.py:1530]		Plotting with roots = ['gaussian']
2020-04-27 14:23:08 [DEBUG]	[mainwindow.py:1566]		Triangle plot with params = ['a', 'b']
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1461]		a 1D sigma_range, std: 0.30348697421831744, 0.30348697421831744; smooth_1D_bins: 82.17558659769597 
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1461]		b 1D sigma_range, std: 0.415841284432462, 0.415841284432462; smooth_1D_bins: 66.94876087351646 
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1654]		Doing 2D: a - b
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1655]		sample x_err, y_err, correlation: 0.30348697421831744, 0.415841284432462, 0.2911456738999044
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1223]		a b AutoBandwidth2D: N_eff=763.170575926697, corr=0.2911456738999044
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1295]		hx/sig, hy/sig, corr =0.36535980185458083, 0.40201186926264276, 0.2646014554793949
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1300]		hx/sig, hy/sig, corr, scale =0.6255877309633849, 0.6883452745369735, 0.2646014554793949, 1.7122511228325525
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1704]		corr, rx, ry: 0.2646014554793949, 23.546287680813432, 20.60078959883917
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1716]		time 2D binning and bandwidth: 0.1943345069885254 ; bins: 256
2020-04-27 14:23:08 [DEBUG]	[mcsamples.py:1799]		time 2D convolutions: 0.19409441947937012
2020-04-27 14:23:08 [DEBUG]	[font_manager.py:1246]		findfont: Matching sans\-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=8.775.

... lots more lines about fonts ...

2020-04-27 14:23:09 [DEBUG]	[font_manager.py:1281]		findfont: Matching sans\-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=11.775 to DejaVu Sans ('/home/jdh4/.conda/envs/gd-env/lib/python3.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
Traceback (most recent call last):
  File "/home/jdh4/.conda/envs/gd-env/lib/python3.7/site-packages/getdist/gui/mainwindow.py", line 1686, in plotData
    self.errorReport(e, caption=actionText)
  File "/home/jdh4/.conda/envs/gd-env/lib/python3.7/site-packages/getdist/gui/mainwindow.py", line 1575, in plotData
    self.updatePlot()
  File "/home/jdh4/.conda/envs/gd-env/lib/python3.7/site-packages/getdist/gui/mainwindow.py", line 1706, in updatePlot
    self.toolbar = NavigationToolbar(self.canvas, self)
  File "/home/jdh4/.conda/envs/gd-env/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 679, in __init__
    QtWidgets.QToolBar.__init__(self, parent)
TypeError: arguments did not match any overloaded call:
  QToolBar(str, parent: QWidget = None): argument 1 has unexpected type 'MainWindow'
  QToolBar(parent: QWidget = None): argument 1 has unexpected type 'MainWindow'

**Comment by cmbant** [comment]
This seems to randomly change between conda-forge builds. Try this, which appears to work for me with your latest env and a somewhat older one
https://github.com/cmbant/getdist/commit/cdb5a353920a1d8d8c0cbcac8d2446ae6a8c7f54

**Comment by jdh4** [comment]
Thanks, cmbant. Yes that works.
